// Generated by CoffeeScript 1.4.0
(function() {
  var template,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  template = "<div class=\"modal hide fade\">\n  <div class=\"modal-header\">\n    <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\n    <h3> Authorize Meet Mikey </h3>\n  </div>\n  <div class=\"modal-body\">\n    <p>You must authorize Meet Mikey to use our awesome features.</p>\n  </div>\n  <div class=\"modal-footer\">\n    <a href=\"#\" id=\"not-now-button\" class=\"btn\">Not Now</a>\n    <a href=\"#\" id=\"authorize-button\" class=\"btn btn-primary\">Authorize</a>\n  </div>\n</div>";

  MeetMikey.View.OnboardModal = (function(_super) {

    __extends(OnboardModal, _super);

    function OnboardModal() {
      this.authorize = __bind(this.authorize, this);

      this.hide = __bind(this.hide, this);

      this.show = __bind(this.show, this);

      this.postRender = __bind(this.postRender, this);
      return OnboardModal.__super__.constructor.apply(this, arguments);
    }

    OnboardModal.prototype.template = Handlebars.compile(template);

    OnboardModal.prototype.events = {
      'click #authorize-button': 'authorize',
      'click #not-now-button': 'hide'
    };

    OnboardModal.prototype.postRender = function() {
      return this.show();
    };

    OnboardModal.prototype.show = function() {
      return this.$('.modal').modal('show');
    };

    OnboardModal.prototype.hide = function() {
      return this.$('.modal').modal('hide');
    };

    OnboardModal.prototype.authorize = function() {
      var _this = this;
      MeetMikey.Helper.OAuth.openAuthWindow(function(data) {
        return _this.trigger('authorized', data);
      });
      return this.hide();
    };

    return OnboardModal;

  })(MeetMikey.View.Base);

}).call(this);
