// Generated by CoffeeScript 1.4.0
(function() {
  var Setup,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Setup = (function() {

    function Setup() {
      this.injectMainView = __bind(this.injectMainView, this);

      this.injectModal = __bind(this.injectModal, this);

      this.initalizeGlobalUser = __bind(this.initalizeGlobalUser, this);

      this.authorized = __bind(this.authorized, this);

      this.setup = __bind(this.setup, this);

      this.bootstrap = __bind(this.bootstrap, this);

      this.start = __bind(this.start, this);

    }

    Setup.prototype.targetSelector = '.UI';

    Setup.prototype.start = function() {
      return $(window).one('DOMSubtreeModified', this.bootstrap);
    };

    Setup.prototype.bootstrap = function() {
      var target;
      console.log('trying to bootstrap');
      target = $(this.targetSelector);
      if (target.length > 0) {
        return this.setup(target);
      } else {
        return window.setTimeout(this.bootstrap, 200);
      }
    };

    Setup.prototype.setup = function(target) {
      var _this = this;
      return MeetMikey.Helper.OAuth.refresh(function(userData) {
        if (userData != null) {
          return _this.authorized(userData);
        } else {
          return _this.injectModal();
        }
      });
    };

    Setup.prototype.authorized = function(userData) {
      this.initalizeGlobalUser(userData);
      return this.injectMainView();
    };

    Setup.prototype.initalizeGlobalUser = function(data) {
      return MeetMikey.globalUser = new MeetMikey.Model.User(data);
    };

    Setup.prototype.injectModal = function() {
      var view,
        _this = this;
      $('body').append($('<div id="mm-onboard-modal"></div>'));
      view = new MeetMikey.View.OnboardModal({
        el: '#mm-onboard-modal'
      });
      view.render();
      return view.on('authorized', function(userData) {
        return _this.authorized(userData);
      });
    };

    Setup.prototype.injectMainView = function(target) {
      var view;
      if (target == null) {
        target = $(this.targetSelector);
      }
      target.before($('<div id="mm-container"></div>'));
      view = new MeetMikey.View.Main({
        el: '#mm-container'
      });
      return view.render();
    };

    return Setup;

  })();

  MeetMikey.Helper.Setup = new Setup();

}).call(this);
