// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  MeetMikey.Decorator.Link = (function() {

    function Link(model) {
      this.model = model;
      this.formatDate = __bind(this.formatDate, this);

      this.formatRecipients = __bind(this.formatRecipients, this);

      this.title = this.model.get('mailCleanSubject');
      this.url = this.model.get('url');
      this.from = this.model.get('sender');
      this.to = this.formatRecipients();
      this.sentDate = this.formatDate();
    }

    Link.prototype.formatRecipients = function() {
      return MeetMikey.Helper.formatRecipients(this.model.get('recipients'));
    };

    Link.prototype.formatDate = function() {
      return MeetMikey.Helper.formatDate(this.model.get('sentDate'));
    };

    return Link;

  })();

}).call(this);
