// Generated by CoffeeScript 1.4.0
(function() {
  var LocalStore,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  LocalStore = (function() {

    function LocalStore(args) {
      this.args = args;
      this.clear = __bind(this.clear, this);

      this.remove = __bind(this.remove, this);

      this.set = __bind(this.set, this);

      this.get = __bind(this.get, this);

      this.store = window.localStorage;
    }

    LocalStore.prototype.supportsLocalStorage = function() {
      return typeof window.localStorage !== 'undefined';
    };

    LocalStore.prototype.get = function(key) {
      return JSON.parse(this.store.getItem(key));
    };

    LocalStore.prototype.set = function(key, value) {
      return this.store.setItem(key, JSON.stringify(value));
    };

    LocalStore.prototype.remove = function(key) {
      return this.store.removeItem(key);
    };

    LocalStore.prototype.clear = function() {
      return this.store.clear();
    };

    return LocalStore;

  })();

  MeetMikey.Helper.LocalStore = new LocalStore();

}).call(this);
