// Generated by CoffeeScript 1.4.0
(function() {

  window.MeetMikey = {
    View: {},
    Model: {},
    Collection: {},
    Decorator: {},
    Template: {},
    Helper: {},
    Settings: {
      APIUrl: "https://local.meetmikey.com"
    }
  };

}).call(this);
