// Generated by CoffeeScript 1.4.0
(function() {

  Handlebars.registerHelper('getAPIUrl', function() {
    return MeetMikey.Settings.APIUrl;
  });

  MeetMikey.Helper.formatDate = function(timestamp) {
    var date, day, month, year;
    date = new Date(timestamp);
    month = date.getMonth() + 1;
    day = date.getDate();
    year = date.getFullYear().toString().slice(-2);
    return "" + month + "/" + day + "/" + year;
  };

  MeetMikey.Helper.formatRecipients = function(recipients) {
    return _.map(recipients, function(r) {
      return r.name || r.email;
    }).join(', ');
  };

}).call(this);
