// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  MeetMikey.Model.Attachment = (function(_super) {

    __extends(Attachment, _super);

    function Attachment() {
      return Attachment.__super__.constructor.apply(this, arguments);
    }

    Attachment.prototype.idAttribute = "_id";

    return Attachment;

  })(Backbone.Model);

}).call(this);
